language: c

os:
  - linux

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install ninja python3-pip build-essential
  - sudo pip3 install --upgrade pip
  - sudo pip3 install meson

script:
  - mkdir builddir
  - meson builddir
  - cd builddir
  - ninja
  - ninja test
