def build(bld):
    obj = bld.create_obj('cc', 'program')
    obj.source = 'random-test-slave.c'
    obj.includes = '. ..'
    obj.uselib_local = 'modbus'
    obj.target = 'random-test-slave'
    obj.inst_var = 0

    obj = bld.create_obj('cc', 'program')
    obj.source = 'random-test-master.c'
    obj.includes = '. ..'
    obj.uselib_local = 'modbus'
    obj.target = 'random-test-master'
    obj.inst_var = 0

    obj = bld.create_obj('cc', 'program')
    obj.source = 'unit-test-slave.c'
    obj.includes = '. ..'
    obj.uselib_local = 'modbus'
    obj.target = 'unit-test-slave'
    obj.inst_var = 0

    obj = bld.create_obj('cc', 'program')
    obj.source = 'unit-test-master.c'
    obj.includes = '. ..'
    obj.uselib_local = 'modbus'
    obj.target = 'unit-test-master'
    obj.inst_var = 0

    obj = bld.create_obj('cc', 'program')
    obj.source = 'bench-bandwidth-slave.c'
    obj.includes = '. ..'
    obj.uselib_local = 'modbus'
    obj.target = 'bench-bandwidth-slave'
    obj.inst_var = 0

    obj = bld.create_obj('cc', 'program')
    obj.source = 'bench-bandwidth-master.c'
    obj.includes = '. ..'
    obj.uselib_local = 'modbus'
    obj.target = 'bench-bandwidth-master'
    obj.inst_var = 0
