def build(bld):
    obj = bld.create_obj('cc', 'program')
    obj.source = 'test-modbus-master.c'
    obj.includes = '. ..'
    obj.uselib_local = 'modbus'
    obj.target = 'test-modbus-master'
    obj.inst_var = 0

    obj = bld.create_obj('cc', 'program')
    obj.source = 'test-modbus-slave.c'
    obj.includes = '. ..'
    obj.uselib_local = 'modbus'
    obj.target = 'test-modbus-slave'
    obj.inst_var = 0
